server:
  port: 8080
spring:
#   application:
#     name: DEPARTMENT-SERVICE
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/department_db
    username: kevinjia
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop # clean   each time
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
app:
  message: this is a message in department service test version 3
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 0.1
logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'
